export const ACADEMIC_GENERACION_TEMPLATES: Record<string, string> = {
  ensayo: `Actúa como {{#if context}}un académico especializado en {{context}}{{else}}un profesor universitario{{/if}}. Redacta un ensayo académico sobre {{topic}}.\n\nEstructura:\n1. Introducción: presenta la tesis central y su relevancia académica\n2. Marco teórico: sintetiza las principales corrientes que abordan el tema\n3. Argumentación: desarrolla al menos tres argumentos sustentados con evidencia\n4. Contra-argumentos y réplicas: anticipa objeciones y respóndelas\n5. Conclusión: resume la tesis, implicaciones y líneas de investigación futuras\n\n{{#if nivel}}Nivel académico: {{nivel}}.{{/if}}\n{{#if isPhilosophy}}Incluye referencias a autores clásicos y contemporáneos de la tradición filosófica.{{/if}}\n{{#if isLiterature}}Analiza recursos retóricos, estructura narrativa y relaciones intertextuales.{{/if}}\n\nUsa lenguaje académico formal y cita fuentes cuando sea pertinente.`,

  resumen: `Actúa como {{#if context}}un investigador en {{context}}{{else}}un académico experimentado{{/if}}. Genera un resumen académico estructurado sobre {{topic}}.\n\nFormato:\n1. Objetivo o propósito del texto original\n2. Metodología o enfoque utilizado (si aplica)\n3. Hallazgos o argumentos principales (3-5 puntos)\n4. Conclusiones e implicaciones\n5. Palabras clave relevantes\n\n{{#if isScience}}Incluye datos cuantitativos clave y muestras representativas.{{/if}}\n{{#if isEconomics}}Resume tendencias, métricas y proyecciones principales.{{/if}}\n\nMáximo 300 palabras. Tono académico conciso.`,

  introduccion: `Actúa como {{#if context}}un investigador en {{context}}{{else}}un académico{{/if}}. Escribe una introducción académica para un trabajo sobre {{topic}}.\n\nDebe contener:\n1. Planteamiento del problema o pregunta de investigación\n2. Justificación de la relevancia académica y práctica\n3. Revisión breve del estado del arte (2-3 enfoques previos)\n4. Objetivo general y específicos de manera clara\n5. Hipótesis o tesis central (si aplica)\n\n{{#if isPsychology}}Menciona instrumentos de medición o marcos teóricos prevalentes.{{/if}}\n{{#if isHistory}}Contextualiza temporal y espacialmente el objeto de estudio.{{/if}}\n\nTono formal, citando autores representativos.`,

  abstract: `Actúa como {{#if context}}un investigador en {{context}}{{else}}un académico{{/if}}. Escribe un abstract académico sobre {{topic}}.\n\nEstructura (150-250 palabras):\n1. Contexto y objetivo de la investigación\n2. Metodología o enfoque teórico\n3. Principales resultados o argumentos\n4. Conclusiones e implicaciones\n\n{{#if isScience}}Incluye muestra, diseño experimental y medidas clave.{{/if}}\n{{#if isMath}}Menciona el método de prueba o demostración principal.{{/if}}\n\nUsa lenguaje impersonal y preciso.`,

  hipotesis: `Actúa como {{#if context}}un metodólogo en {{context}}{{else}}un investigador experimentado{{/if}}. Formula una hipótesis de investigación sobre {{topic}}.\n\nDebe incluir:\n1. Planteamiento del problema observable\n2. Revisión breve de evidencia previa\n3. Hipótesis principal formulada de manera operacional (relación entre variables)\n4. Hipótesis alternativas (si aplica)\n5. Criterios de falsabilidad o validación propuestos\n\n{{#if isScience}}Especifica variables independientes, dependientes y posibles confusoras.{{/if}}\n{{#if isPsychology}}Considera marcos teóricos cognitivo, conductual o psicoanalítico según pertinencia.{{/if}}\n\nTono académico riguroso y preciso.`,
};
