export const ACADEMIC_ANALISIS_TEMPLATES: Record<string, string> = {
  critica: `Actúa como {{#if context}}un crítico académico en {{context}}{{else}}un investigador experto{{/if}}. Realiza un análisis crítico de {{topic}}.\n\nEstructura:\n1. Presentación del objeto de análisis y su contexto\n2. Resumen imparcial de las posturas principales\n3. Análisis de fortalezas metodológicas o argumentativas\n4. Identificación de debilidades, sesgos o limitaciones\n5. Propuesta de mejoras o líneas de investigación futuras\n6. Conclusión valorativa fundamentada\n\n{{#if isPhilosophy}}Evalúa la validez lógica, la solidez de las premisas y la coherencia con la tradición filosófica.{{/if}}\n{{#if isLiterature}}Analiza recursos retóricos, estructura narrativa, contexto histórico del autor y recepción crítica.{{/if}}\n{{#if isHistory}}Considera fuentes primarias vs secundarias, perspectivas historiográficas y posibles sesgos narrativos.{{/if}}\n\nMantén objetividad académica y fundamenta cada juicio.`,

  comparacion: `Actúa como {{#if context}}un investigador comparatista en {{context}}{{else}}un académico multidisciplinario{{/if}}. Realiza un análisis comparativo académico de {{topic}}.\n\nEstructura:\n1. Justificación de la comparación y criterios seleccionados\n2. Descripción de cada elemento según los criterios\n3. Análisis de similitudes estructurales o conceptuales\n4. Análisis de diferencias significativas\n5. Tabla comparativa sintetizada\n6. Conclusión sobre implicaciones teóricas o prácticas\n\n{{#if isScience}}Incluye métricas cuantitativas de comparación cuando sea posible.{{/if}}\n{{#if isEconomics}}Compara indicadores de rendimiento, costo-beneficio y contextos regulatorios.{{/if}}\n\nTono objetivo y riguroso.`,

  argumentacion: `Actúa como {{#if context}}un lógico o argumentador en {{context}}{{else}}un filósofo analítico{{/if}}. Evalúa la solidez argumentativa de {{topic}}.\n\nEstructura:\n1. Reconstrucción formal del argumento (premisas y conclusión)\n2. Evaluación de la validez lógica\n3. Evaluación de la solidez o verdad de las premisas\n4. Identificación de falacias o sesgos argumentativos\n5. Análisis de supuestos implícitos\n6. Veredicto y recomendaciones de mejora\n\n{{#if isPhilosophy}}Sitúa el argumento dentro de su tradición filosófica y menciona críticas canónicas.{{/if}}\n{{#if isLaw}}Evalúa la coherencia con el marco normativo y la jurisprudencia relevante.{{/if}}\n\nUsa lenguaje preciso y estructura lógica clara.`,

  metodologia: `Actúa como {{#if context}}un metodólogo en {{context}}{{else}}un investigador experimentado{{/if}}. Analiza la metodología empleada en {{topic}}.\n\nEstructura:\n1. Tipo de investigación (exploratoria, descriptiva, correlacional, experimental, etc.)\n2. Diseño metodológico y su adecuación al objetivo\n3. Población y muestra (tamaño, técnica de selección, representatividad)\n4. Instrumentos de recolección de datos (validación y confiabilidad)\n5. Procedimiento de análisis de datos\n6. Fortalezas y limitaciones metodológicas\n7. Recomendaciones de mejora\n\n{{#if isScience}}Evalúa la replicabilidad y el control de variables.{{/if}}\n{{#if isPsychology}}Considera validez interna, externa, constructo y confiabilidad inter-jueces.{{/if}}\n\nTono técnico pero accesible para académicos de áreas afines.`,
};
