export const ACADEMIC_INFORMACION_TEMPLATES: Record<string, string> = {
  definicion: `Actúa como {{#if context}}un experto académico en {{context}}{{else}}un profesor universitario{{/if}} con capacidad para explicar conceptos de forma rigurosa y accesible.\n\nTu tarea: define y explica {{topic}} de forma completa.\n\nEstructura tu respuesta así:\n1. Definición formal (máximo 3 oraciones)\n2. Contexto y origen del concepto\n3. Componentes o elementos clave\n4. Aplicaciones principales{{#if nivel}} adaptadas a nivel {{nivel}}{{/if}}\n5. Un ejemplo concreto ilustrativo\n\n{{#if isMath}}Incluye la notación formal correspondiente y al menos un ejemplo numérico resuelto paso a paso.{{/if}}\n{{#if isScience}}Menciona el sustento empírico o experimental del concepto.{{/if}}\n{{#if isHistory}}Ubica el concepto en su contexto histórico y menciona su legado.{{/if}}\n{{#if isPsychology}}Indica las corrientes psicológicas que abordan este concepto y sus diferencias de enfoque.{{/if}}\n\nResponde en español con lenguaje académico claro.`,

  explicacion_tecnica: `Actúa como {{#if context}}un investigador especializado en {{context}}{{else}}un académico experimentado{{/if}}. Explica {{topic}} con rigor metodológico{{#if nivel}} a nivel {{nivel}}{{/if}}.\n\nTu respuesta debe incluir:\n1. Antecedentes teóricos fundamentales\n2. Desarrollo del concepto o fenómeno paso a paso\n3. Evidencia empírica o demostración formal{{#if isMath}} con notación matemática precisa{{/if}}\n4. Aplicaciones actuales en investigación o práctica profesional\n5. Limitaciones o debates abiertos en la literatura\n\n{{#if isScience}}Cita al menos dos estudios o experimentos clave que sustenten la explicación.{{/if}}\n{{#if isEconomics}}Incluye datos cuantitativos o tendencias de mercado cuando sea pertinente.{{/if}}\n\nUsa lenguaje académico preciso pero accesible.`,

  comparacion: `Actúa como {{#if context}}un académico en {{context}}{{else}}un investigador multidisciplinario{{/if}}. Realiza una comparación académica de {{topic}}.\n\nEstructura tu análisis así:\n1. Marco teórico de comparación (criterios explícitos)\n2. Análisis punto por punto según los criterios establecidos\n3. Evidencia empírica o argumentación lógica para cada punto\n4. Tabla comparativa sintetizada\n5. Conclusión argumentada sobre ventajas, limitaciones y contextos de aplicación\n\n{{#if isHistory}}Considera el contexto temporal, geográfico y socio-político de cada elemento comparado.{{/if}}\n{{#if isLiterature}}Analiza recursos retóricos, estructura narrativa y contexto de producción de cada obra.{{/if}}\n\nMantén un tono objetivo y académico.`,

  ejemplo: `Actúa como {{#if context}}un docente universitario en {{context}}{{else}}un profesor investigador{{/if}}. Proporciona ejemplos académicos sobre {{topic}}.\n\nPara cada ejemplo:\n1. Presenta el caso o problema concreto\n2. Explica la teoría o principio que ilustra\n3. Desarrolla el ejemplo paso a paso{{#if isMath}} incluyendo cálculos detallados{{/if}}\n4. Relaciona con la literatura académica existente\n5. Indica las limitaciones o alcances del ejemplo\n\n{{#if nivel}}Adapta la complejidad al nivel {{nivel}}.{{/if}}\n\nProporciona al menos tres ejemplos de distinta naturaleza (teórico, aplicado, crítico).`,
};
