import '../test-utils/setup-chrome';
import '../service-worker';

describe('Service Worker', () => {
  const mockChrome = (global as any).chrome;

  // Capture handlers immediately after module load
  const onMessageHandler = mockChrome.runtime.onMessage.addListener.mock.calls[0]?.[0] as Function | undefined;
  const onInstalledHandler = mockChrome.runtime.onInstalled.addListener.mock.calls[0]?.[0] as Function | undefined;

  beforeEach(() => {
    // Only clear message-related mocks, not addListener registration mocks
    mockChrome.runtime.sendMessage.mockClear();
    mockChrome.tabs.sendMessage.mockClear();
    mockChrome.sidePanel.open.mockClear();
  });

  it('registers onInstalled and onMessage listeners on load', () => {
    expect(onInstalledHandler).toBeDefined();
    expect(onMessageHandler).toBeDefined();
  });

  it('triggers pipeline initialization on install', () => {
    expect(() => onInstalledHandler!({ reason: 'install' })).not.toThrow();
  });

  it('opens side panel on OPEN_PANEL message', () => {
    const sendResponse = jest.fn();
    const result = onMessageHandler!({ type: 'OPEN_PANEL' }, { tab: { id: 123 } }, sendResponse);

    expect(mockChrome.sidePanel.open).toHaveBeenCalledWith({ tabId: 123 });
    expect(sendResponse).toHaveBeenCalledWith({ ok: true });
    expect(result).toBe(false);
  });

  it('returns questions on GET_QUESTIONS message', async () => {
    const sendResponse = jest.fn();
    const result = onMessageHandler!(
      { type: 'GET_QUESTIONS', payload: { text: 'explicame que es la recursividad' } },
      {},
      sendResponse
    );

    expect(result).toBe(true);

    // Wait for async processing
    await new Promise(resolve => setTimeout(resolve, 300));
    expect(sendResponse).toHaveBeenCalled();
    const response = sendResponse.mock.calls[0][0];
    expect(response.questions).toBeDefined();
    expect(Array.isArray(response.questions)).toBe(true);
  });

  it('processes prompt on PROCESS_PROMPT message', async () => {
    const sendResponse = jest.fn();

    // 1. Signal panel is ready
    onMessageHandler!({ type: 'PANEL_READY' }, {}, sendResponse);

    // 2. Process prompt
    const result = onMessageHandler!(
      { type: 'PROCESS_PROMPT', payload: { text: 'explicame que es la recursividad' } },
      { tab: { id: 456 } },
      sendResponse
    );

    expect(result).toBe(true);

    // Wait for SHOW_QUESTIONS and listener registration
    await new Promise(resolve => setTimeout(resolve, 100));

    // 3. Simulate user answering questions
    // Since Phase 5, LayerB checks originalPrompt and sessionId
    const listeners = mockChrome.runtime.onMessage.addListener.mock.calls
      .map((call: unknown[]) => call[0] as (msg: { type: string; payload?: unknown }) => void);
    
    // We don't have the exact sessionId generated by LayerB in the test easily, 
    // but the listener is an inline function in promptUser that captures the sessionId from scope.
    // Wait, the listener captures sessionId from its scope. The message just needs to match.
    // We should mock crypto.randomUUID if we need to know it, but we can't easily.
    // Actually, LayerB sends a SHOW_QUESTIONS message that has the sessionId. Let's intercept it.
    const showQuestionsCall = mockChrome.runtime.sendMessage.mock.calls.find(
      (call: any[]) => call[0]?.type === 'SHOW_QUESTIONS' && call[0]?.payload?.sessionId
    );
    const sessionId = showQuestionsCall ? showQuestionsCall[0].payload.sessionId : undefined;

    for (const listener of listeners) {
      listener({ 
        type: 'QUESTIONS_ANSWERED', 
        payload: { 
          answers: {}, 
          originalPrompt: 'explicame que es la recursividad', 
          sessionId 
        } 
      });
    }

    // Wait for async processing
    await new Promise(resolve => setTimeout(resolve, 300));

    expect(mockChrome.tabs.sendMessage).toHaveBeenCalledWith(
      456,
      expect.objectContaining({ type: 'PIPELINE_RESULT' })
    );
    expect(mockChrome.runtime.sendMessage).toHaveBeenCalledWith(
      expect.objectContaining({ type: 'DISPLAY_RESULT' })
    );
  });
});
